version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo "Setting up environment variables"
      - cat buildspec.yml
      - echo "ENVIRONMENT_DEV is ${ENVIRONMENT_DEV}"
      - echo "ENVIRONMENT_PROD is ${ENVIRONMENT_PROD}"

  build:
    commands:
      - ./print_env.sh

artifacts:
  files:
    - print_env.sh
