version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo "Setting up environment variables"
      - echo "ENVIRONMENT_DEV is ${ENVIRONMENT_DEV}"
      - echo "ENVIRONMENT_PROD is ${ENVIRONMENT_PROD}"

  build:
    commands:
      - echo "Using environment: ${ENVIRONMENT_DEV}" # or ${ENVIRONMENT_PROD} depending on your requirement
      - ./print_env.sh

artifacts:
  files:
    - print_env.sh
