version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Setting up environment variables"
      - echo "CODEBUILD_SOURCE_VERSION ${CODEBUILD_SOURCE_VERSION}"
      - echo "Environment: $ENVIRONMENT"
  build:
    commands:
      - ./print_env.sh
