version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Setting up environment variables"
      - if [ "$CODEBUILD_SOURCE_VERSION" == "refs/heads/dev" ]; then export ENVIRONMENT="development"; fi
      - if [ "$CODEBUILD_SOURCE_VERSION" == "refs/heads/prod" ]; then export ENVIRONMENT="production"; fi
      - echo "Environment: $ENVIRONMENT"
  build:
    commands:
      - ./print_env.sh
  post_build:
    commands:
      - ./deploy.sh
