version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo "Setting up environment variables"
      - echo "CODEBUILD_SOURCE_VERSION is ${CODEBUILD_SOURCE_VERSION}"
      - |
        if [ -n "$CODEBUILD_WEBHOOK_HEAD_REF" ]; then
          BRANCH_NAME=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}
        else
          BRANCH_NAME=${CODEBUILD_SOURCE_VERSION#refs/heads/}
        fi
        echo "Branch name: $BRANCH_NAME"
        if [ "$BRANCH_NAME" == "dev" ]; then
          export ENVIRONMENT=${ENVIRONMENT_DEV}
        elif [ "$BRANCH_NAME" == "main" ]; then
          export ENVIRONMENT=${ENVIRONMENT_PROD}
        else
          export ENVIRONMENT="unknown"
        fi
        echo "Environment: $ENVIRONMENT"

  build:
    commands:
      - echo "Running build for environment: $ENVIRONMENT"
      - ./print_env.sh

artifacts:
  files:
    - print_env.sh
